name: EditorConfig Checker

on:
  push:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'
