name: EditorConfig Checker

on:
  pull_request:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "zbeekman/EditorConfig-Action@v1.1.0"
        env:
          ALWAYS_LINT_ALL_FILES: false # This is the default
