name: EditorConfig Checker

on:
  push:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'
